site_name: FlaskData Documentations
nav:
  - Home: index.md
  - Getting Started:
    - Registration: registration.md
    - First Study: first_study.md
    - Manage Studies: manage_studies.md
    - Manage Sites: manage_sites.md
    - Manage Users: manage_users.md
    - Manage Forms: manage_forms.md
    - Manage Subjects: manage_subjects.md
    - Manage Data: manage_data.md
  - Extras:
    - Study Dashboard: study_dashboard.md
    - Metrics: manage_metrics.md
    - Tools: tools.md
    - Features: manage_features.md
    - Manage Queries: manage_queries.md
    - EDC: edc.md
    - Flask and EDC: flask_and_edc.md
  - FlaskData API:
    - API Introduction: api_introduction.md
    - API Flows: apiflows.md
  - ePRO :
      - Flask ePRO: epro.md
      - ePRO Mobile: epro_mobile.md
      - ePRO Desktop: epro_desktop.md
      - Instructions for patient diary: epro_patient_instructions.md
theme:
  name: 'material'
  logo: 'img/logo.PNG'
  favicon: 'img/favicon.PNG'
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
